### PR TITLE
Some small improvements

### PR DESCRIPTION
**Pull request by luckman212**
This adds a setting for **separator** string (can be anything, but defaults to ` - `) and allows for dynamic removal of unpopulated moustache templates to keep the title clean. Another small QoL improvement is I made the settings fields larger so they don't cut off, and set them to `monospace` type. Also adds a `{{version}}` placeholder to display the app version (similar to the default title).

To use it, separate your `{{moustache}}` placeholders with `%%` to have the separator dynamically inserted. 

_example settings:_

image

### CODE REVIEW

**Comment by luckman212** [comment]
Not sure why GitHub is marking every single line as a change here when clearly it's not -- something about whitespace maybe? Sorry @jplattel not sure how to correct that. If you download the source and diff it with standard tools you'll easily see the changes...

image

**Comment by Moonbase59** [comment]
@luckman212 @jplattel I’d _never_ use tabs in source code—leads to endless problems. I actually forbade it in teams I led. Leaving an `.editorconfig` file in the root helps: Most modern editors respect that (or can be set to).

**Comment by luckman212** [comment]
@jplattel I just pushed another update that addresses some concerns. @Moonbase59 if you don't have a dev setup, you can grab a compiled `main.js` from [here](https://gist.github.com/luckman212/967fa2bd6d14afd3ecd7b0ca02f9b6a0) and just replace your existing on to give it a try.

**Comment by luckman212** [comment]
@Moonbase59 latest version ([gist](https://gist.github.com/luckman212/967fa2bd6d14afd3ecd7b0ca02f9b6a0)) removes the electron dependency... as you requested. LMK!

**Comment by luckman212** [comment]
I pushed another update:

- adds an event listener for `metadataCache.on('changed')` so the title with moustache template can respond to YAML changes while working
- adds a workaround (3s delay) to rename handler, since there's a race condition between when the callback is triggered and the metadataCache is updated, which causes the title to be missing the frontmatter tags. This small delay fixes it, but I'm sure there's a better way (maybe @lishid knows...)

**Comment by Moonbase59** [comment]
Good move on the `metadataCache`! Already in the gist?

**Comment by luckman212** [comment]
Yes the gist is up to date. @Moonbase59

**Comment by Moonbase59** [comment]
Testing … I’ve used this setup:

Auswahl_120

- The idea for the "no file open" string was:
  - Show "Vault - Obsidian 0.12.12" when there _is_ a vault open.
  - Show "Obsidian 0.12.12" when there is _no_ vault open (can that happen?)
- The idea of the "file open" string (some of my notes have a `date:` in YAML, some don’t):
  - If date is in the YAML, display "Filename (date) - Vault - Obsidian 0.12.12"
  - If no date, display "Filename - Vault - Obsidian 0.12.12" _(haha, another level of complexity!)_, or at least "Filename () - Vault - Obsidian 0.12.12"

The former ones display as
- `Vault%%Obsidian 0.12.12`,

the latter ones as either
- `Vault%%Obsidian 0.12.12` (if no date in YAML), or
- `Filename.md (date) - Vault%%Obsidian 0.12.12`

This _is_ a rather unfair example, I know, but that’s how users _think_. I wonder if and how this could/should be solved, let’s discuss, if you wish.

Three general suggestions:
- Can we show the "Filename" part _without extension if `.md`_ and _with extension if not_, like Obsidian does (say, for a `.png`)? Or use another variable for that, like `{{filetitle}}`?
- I somehow feel the removal of elements should be _successive_. Currently, if there’s no `date` in above example, _all_ elements to the left of the `%%` are removed, not just the _next_ (the date). This means we have no filename.
- I’d stick the `%%` into a variable instead of hard-coding it in the RegEx. Maybe even make it configurable—a user might _want_ to use `%%` in the string, for whatever reason.

For the removal of "other text" like the `()` surrounding my `{{frontmatter.date}}`, one might thing of also removing any non-whitespace _directly adjacent_ to a variable. Do you see any side effects in this?

For the `%%` used between a template var and normal text (like in `{{vault}}%%Obsidian` above), one could think of doing a _one-sided_ replace, i.e. display "Vault - Obsidian" if `{{vault}}` is non-empty, and "Obsidian" otherwise. See any possible side effects?

**Comment by luckman212** [comment]
Ah, good ideas . Give me a short while @Moonbase59

**Comment by luckman212** [comment]
Didn't realize renaming the branch auto-closes the PR (TIL). I was just fixing a typo in the branch name.... well anyway I am uploading the changes now

**Comment by luckman212** [comment]
@Moonbase59 I implemented some more changes... gist has been updated if you want to test.

I couldn't come up with a reasonable way to do "remove non-whitespace directly adjacent to a variable" -- any ideas?

**Comment by lishid** [comment]
There's an undocumented function at `metadataCache.onCleanCache(callback)`.

**Comment by luckman212** [comment]
Thanks @lishid 🙏 
I am trying to incorporate that API but I'm not seeing it get triggered on rename. Does renaming a file trigger a metadataCache update? Seems iike maybe it doesn't? Any help greatly appreciated !!

**Comment by luckman212** [comment]
Update: @lishid [this version (gist)](https://gist.github.com/luckman212/60941fe2d6246f0c7c77bcf5b2003f2b) works, but throws js errors in the console:
```js
app.js:1 TypeError: e is not a function
    at t.checkCleanCache (app.js:1)
    at t.e.tryTrigger (app.js:1)
    at t.e.trigger (app.js:1)
    at t.trigger (app.js:1)
    at e.onStop (app.js:1)
    at e.stop (app.js:1)
    at e.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at a (app.js:1)
```
any hint on how to properly register this callback? 🙏

**Comment by luckman212** [comment]
@lishid I think through a lot of hair pulling and trial and error I got it working.... 
is this right?
```ts
private readonly handleRename = async (file: TFile, oldPath: string): Promise<void> => {
  if (file instanceof TFile && file === this.app.workspace.getActiveFile()) {
    this.app.metadataCache.onCleanCache(async (): Promise<void> => { this.refreshTitle(file); });
  }
};
```
@Moonbase59 -- [gist](https://gist.github.com/luckman212/967fa2bd6d14afd3ecd7b0ca02f9b6a0) updated with latest... pls test 🙏

**Comment by Moonbase59** [comment]
@luckman212 Man, you pointed me at PR #11 in Discord, and I was looking … looking … :rofl: 
Testing now … :-)

**Comment by Moonbase59** [comment]
Works:

- Simple replacements like
  ```
  {{basename}}%%{{frontmatter.date}}%%{{vault}}%%Obsidian {{version}}
  ```
- immediate change on file rename

Doesn’t work:

- a filename that displays like in Obsidian (`.md` extension removed, other extensions stay)
- more complex replacements like
  ```
  {{basename}} ({{frontmatter.date}})%%{{vault}}%%Obsidian {{version}}
  ```
  which will display
  ```text
  Test Abstract in YAML (2021-06-10)%%Knowledgebase - Obsidian 0.12.12
  ```
  or
  ```text
  Test audio drop ()%%Knowledgebase - Obsidian 0.12.12
  ```

The idea behind the last one is:

- showing YAML metadata from a file only makes sense if we _have_ a file open
- the parentheses `()` around a date here should signify to a watcher that this _has_ a date (different separator)
- I’d expect _the whole thing_ left oft the first `%%` to "go away" if we had no file open
- and probably even (optionally) be able to remove the `()` around an empty `{{frontmatter.date}}` (i.e., remove adjacent non-whitespace up to next whitespace or separator string or beginning/end of line

Also:

- If using "simple" replacement and have a watching app, it would get confused if one of the variables "in the middle" wouldn’t be there (like 1st example, and no date), and probably shift values into the wrong "registers", because it’d dumbly look for separators.
- I didn’t understand the difference between `%%{{var}}` and `{{var}}%%`—except that it places the separator somewhere else?
- When changing settings (and having a note open), it’ll return the title to be the "no file open" string, instead of checking and using the "file is opened" string.


Well, maybe these extraordinary wishes/ideas might simply not be possible. Before overdoing it, maybe just leave as is.

**Comment by luckman212** [comment]
@Moonbase59 not sure if you're tracking the open PR #11 ... just in case, please have a go with the newest version from over there...

**Pull request closed without merging**
