### PR TITLE
Small fix for rename/delete edge cases

### PR DESCRIPTION
**Pull request by luckman212**
Hey @jplattel 👋 

This small PR fixes 2 edge cases:

1. non-active file renamed from the side panel incorrectly sets the title of the active document
2. deleting non-active file causes title to revert to default even if there is still an open note

(thanks to @pjeby for inspiration from https://github.com/ravimashru/obsidian-show-file-path/pull/3/commits/59c49b771db7d9ac91091ccc78f5ef6ce726db87)

### CODE REVIEW

**Comment by luckman212** [comment]
Sorry for the README.md in here. I copied in the original from `master` but not sure how to just remove it completely from the branch changes. Hope it's ok.

**Comment by jplattel** [comment]
Awesome! Thanks @luckman212! Looks good, I'll merge it 👍

**Comment by luckman212** [comment]
Thanks @jplattel - how does the releasing work? Will it auto update on the Obsidian community repo?

**Comment by jplattel** [comment]
I just need to set a tag, which I'm about to do, it should roll out to Obsidian after that :)

**Pull request merged**
